//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by phthphat
//

import UIKit

class ___VARIABLE_productName:identifier___VC: UIViewController {

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}


#if DEBUG
import SwiftUI
struct Presentable___VARIABLE_productName:identifier___VC: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> ___VARIABLE_productName:identifier___VC {
	let vc = ___VARIABLE_productName:identifier___VC()
	return vc 
    }
    func updateUIViewController(_ uiViewController: ___VARIABLE_productName:identifier___VC, context: Context) { }
}
struct ___VARIABLE_productName:identifier___VCPreview: PreviewProvider {
    static var previews: some View {
        return Presentable___VARIABLE_productName:identifier___VC()
    }
}
#endif
